# Assignment-1: Transformations and representations

Team Name: \<team name here\> 

Roll number: \<Roll number here (in sorted order)\>

# Instructions

- Code must be written in Python in Jupyter Notebooks. We highly recommend using anaconda distribution or at the minimum, virtual environments for this assignment. See `Set Up` for detailed step-by-step instructions about the installation setup.
- Save all your results in ```results/<question_number>/<sub_topic_number>/```
- The **References** section provides you with important resources to solve the assignment.
- For this assignment, you will be using Open3D extensively. Refer to [Open3D Documentation](http://www.open3d.org/docs/release/): you can use the in-built methods and **unless explicitly mentioned**, don't need to code from scratch for this assignment. 
- Make sure your code is modular since you may need to reuse parts for future assignments.
- Answer the descriptive questions in your own words with context & clarity. Do not copy answers from online resources or lecture notes.
- The **deadline** for this assignment is on 11/09/2021 at 11:55pm. Please note that there will be no extensions.
- Plagiarism is **strictly prohibited**.


# Submission Instructions

1. Make sure your code runs without any errors after reinitializing the kernel and removing all saved variables.
2. After completing your code and saving your results, zip the folder with name as ``Team_<team_name>_MR2021_Assignment_<assignment_number>.zip``

# Set Up

We highly recommend using anaconda distribution or at the minimum, virtual environments for this assignment. All assignments will be python based, hence familiarising yourself with Python is essential.


## Setting up Anaconda environment (Recommended)

1. Install Anaconda or Miniconda from [here](https://docs.conda.io/projects/conda/en/latest/user-guide/install/linux.html) depending on your requirements.
2. Now simply run `conda env create -f environment.yml` in the current folder to create an environment `mr_assignment1` (`environment.yml` can be found in `misc/`).
3. Activate it using `conda activate mr_assignment1`.

## Setting up Virtual environment using venv

You can also set up a virtual environment using venv

1. Run `sudo apt-get install python3-venv` from command line.
2. `python3 -m venv ~/virtual_env/mr_assignment1`. (you can set the environment path to anything)
3. `source ~/virtual_env/mr_assignment1/bin/activate`
4. `pip3 install -r requirements.txt` from the current folder (`requirements.txt` can be found in `misc/`).

In [24]:
import open3d as o3d
import numpy as np
from scipy.optimize import fsolve
from scipy.spatial.transform import Rotation

# 1. Getting started with Open3D

Open3D is an open-source library that deals with 3D data, such as point clouds, mesh. We'll be using Open3D frequently as we work with point clouds. Let's start with something simple:

<img src="misc/bunny.jpg" alt="drawing" width="200"/>

1. Read the Stanford Bunny file (in `data/`) given to you and visualise it using Open3D.
2. Convert the mesh to a point cloud and change the colour of points.
3. Set a predefined viewing angle (using Open3D) for visualization and display the axes while plotting.
4. Scale, Transform, and Rotate the rabbit (visualise after each step).
5. Save the point cloud as bunny.pcd.

In [214]:
# Reading Data
mesh = o3d.io.read_triangle_mesh('./data/bunny.ply')
o3d.visualization.draw([mesh])

In [219]:
## Convert Mesh to Point Cloud & Change Color
point_cloud = mesh.sample_points_poisson_disk(5000)
point_cloud.paint_uniform_color([1, 0.5, 0.])
o3d.visualization.draw([point_cloud])

In [220]:
## Show Axis
mesh_frame = o3d.geometry.TriangleMesh.create_coordinate_frame(size=0.03, origin=np.array([0., 0., 0.]))
o3d.visualization.draw([point_cloud, mesh_frame], 
                       lookat=np.array([[.0], [.1], [.0]], dtype=np.float64),
                       eye=np.array([[0.0], [0.0], [-0.4]], dtype=np.float64),
                       up=np.array([[0.0], [0.5], [0.0]], dtype=np.float64),
                      )

In [221]:
## Scale Point Cloud by 0.5
point_cloud.scale(scale=0.5, center=np.array([[.0], [.0], [.0]], dtype=np.float64))
o3d.visualization.draw([point_cloud, mesh_frame],
                       lookat=np.array([[.0], [.1], [.0]], dtype=np.float64),
                       eye=np.array([[0.0], [0.0], [-0.4]], dtype=np.float64),
                       up=np.array([[0.0], [0.5], [0.0]], dtype=np.float64),
                      )

In [222]:
## Transform Point Cloud (Rotate about Y axis, translate to [0.2, 0, 0])
point_cloud.transform(np.array([[0.707, 0.0, 0.707, 0.2],
                                [0.0, 1.0, 0.0, 0.0],
                                [-0.707, 0.0, 0.707, 0.0],
                                [0.0, 0.0, 0.0, 1.0]], dtype=np.float64))
o3d.visualization.draw([point_cloud, mesh_frame],
                       lookat=np.array([[.0], [.1], [.0]], dtype=np.float64),
                       eye=np.array([[0.0], [0.0], [-0.4]], dtype=np.float64),
                       up=np.array([[0.0], [0.5], [0.0]], dtype=np.float64),
                      )

In [223]:
## Rotate Point Cloud (Rotate about Y axis)
point_cloud.rotate(R=np.array([[0.707, 0.0, 0.707],
                                [0.0, 1.0, 0.0],
                                [-0.707, 0.0, 0.707]], dtype=np.float64))
o3d.visualization.draw([point_cloud, mesh_frame],
                       lookat=np.array([[.0], [.1], [.0]], dtype=np.float64),
                       eye=np.array([[0.0], [0.0], [-0.4]], dtype=np.float64),
                       up=np.array([[0.0], [0.5], [0.0]], dtype=np.float64),
                      )

In [8]:
## Save 
o3d.io.write_point_cloud('./data/bunny.pcd', point_cloud)

# 2. Transformations and representations

## a) Euler angles
1. Write a function that returns a rotation matrix given the angles $\alpha$, $\beta$, and $\gamma$ in radians (X-Y-Z)

2. Solve for angles using ```fsolve from scipy``` for three initializations of your choice and compare.
$$M(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0.26200263 & -0.19674724 & 0.944799 \\0.21984631 & 0.96542533 & 0.14007684 \\
    -0.93969262 & 0.17101007 & 0.29619813\end{array}\right] 
$$

$$N(\alpha , \beta ,\gamma)=\left[\begin{array}{rrr}0 & -0.173648178 &  0.984807753 \\0 & 0.984807753 & 0.173648178 \\
    -1 & 0 & 0\end{array}\right] 
$$

3. What is a Gimbal lock? 

4. Show an example where a Gimbal lock occurs and visualize the Gimbal lock on the given bunny point cloud. You have to show the above by **animation** (cube rotating along each axis one by one).
    - *Hint: Use Open3D's non-blocking visualization and discretize the rotation to simulate the animation. For example, if you want to rotate by $30^{\circ}$ around a particular axis, do in increments of $5^{\circ}$ 6 times to make it look like an animation.*


<font color='blue' size=4.0/> 2.a.1 Function that returns a rotation matrix given the angles $\alpha$, $\beta$, and $\gamma$ in radians (X-Y-Z)

In [9]:
## Order can be reverse, Since X-Y-Z angles
def get_rotation_matrix(alpha, beta, gamma):
    r_alpha = np.array([[1.0, 0.0, 0.0],
                        [0.0, np.cos(alpha), -np.sin(alpha)],
                        [0.0, np.sin(alpha), np.cos(alpha)]], dtype=np.float64)
    r_alpha = np.around(r_alpha, decimals=4)

    r_beta = np.array([[np.cos(beta), 0.0, np.sin(beta)],
                        [0.0, 1.0, 0.0],
                        [-np.sin(beta), 0.0, np.cos(beta)]], dtype=np.float64)
    r_beta = np.around(r_beta, decimals=4)

    r_gamma = np.array([[np.cos(gamma), -np.sin(gamma), 0.0],
                        [np.sin(gamma), np.cos(gamma), 0.0],
                        [0.0, 0.0, 1.0]], dtype=np.float64)
    r_gamma = np.around(r_gamma, decimals=3)
    
    return r_alpha @ r_beta @ r_gamma

R = get_rotation_matrix(np.radians(0), np.radians(0), np.radians(0))
print(R)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


<font color='blue' size=4.0/> 2.a.2 Solve for angles using `fsolve from scipy` for three initializations of your choice and compare

In [10]:
M = np.array([[0.26200263, -0.19674724, 0.944799],
              [0.21984631, 0.96542533, 0.14007684],
              [-0.93969262, 0.17101007, 0.29619813]])

N = np.array([[0., -0.173648178, 0.984807753],
              [0., 0.984807753, 0.173648178],
              [-1., 0., 0.]])

In [11]:
def func(x, R):
    return [np.cos(x[0])*np.cos(x[1]) - R[2, 2], np.sin(x[1]) - R[0, 2], np.cos(x[1])*np.cos(x[2]) - R[0, 0]]

In [12]:
x_M = [0.2, 0.1, np.pi/2]
x_M = fsolve(func, x_M, args=M)
print(f"Euler Angles for matrix M using fsolve: {x_M}")

Euler Angles for matrix M using fsolve: [-0.44174658  1.2369806   0.64409993]


In [13]:
x_N = [0.2, 0.1, np.pi/2]
x_N = fsolve(func, x_N, args=N)
print(f"Euler Angles for matrix N using fsolve: {x_N}")

Euler Angles for matrix N using fsolve: [-1.57079633  1.3962634   1.57079633]


In [14]:
R_M = get_rotation_matrix(*x_M)
print("Reconstructed matrix M from predcited angles \n", R_M)

R_N = get_rotation_matrix(*x_N)
print("Reconstructed matrix N from predcited angles \n", R_N)

Reconstructed matrix M from predcited angles 
 [[ 0.26216    -0.19662     0.9448    ]
 [ 0.2192784   0.9655412   0.14009175]
 [-0.93977936  0.17045952  0.2962408 ]]
Reconstructed matrix N from predcited angles 
 [[ 0.     -0.1736  0.9848]
 [ 0.      0.9848  0.1736]
 [-1.      0.      0.    ]]


In [15]:
## Verify (Closed Form)
def rotationToEuler(R):
    return [np.arctan2(-R[1, 2], R[2, 2]), np.arctan2(R[0, 2], np.sqrt(1 - R[0, 2]**2)), np.arctan2(-R[0, 1], R[0, 0])]

print(f'Closed Form Euler Angles for matrix M: {rotationToEuler(M)}')
print(f'Closed Form Euler Angles for matrix N: {rotationToEuler(N)}')

Closed Form Euler Angles for matrix M: [-0.44174662088223243, 1.2369806006375788, 0.6440999603368792]
Closed Form Euler Angles for matrix N: [-1.5707963267948966, 1.3962634015251603, 1.5707963267948966]


<font color='blue' size=4.0/> 2.a.3 What is a Gimbal lock?

Gimbal lock occurs when two of the three axis of rotations become parallel to each other resulting in loss of one degree of freedom and restricting rotation to two dimensional space.

<font color='blue' size=4.0/> 2.a.4 Example of Gimbal lock and visualize the Gimbal lock on the given bunny point cloud

In [225]:
point_cloud = o3d.io.read_point_cloud('./data/bunny.ply')

In [226]:
pcd_list = []

for angle in range(0, 90, 10):
    point_cloud.rotate(R=np.array([[1.0, 0.0, 0.0],
                                   [0.0, np.cos(np.radians(angle)), -np.sin(np.radians(angle))],
                                   [0.0, np.sin(np.radians(angle)), np.cos(np.radians(angle))]], dtype=np.float64))
    pcd_list.append(point_cloud)

## b) Quaternions

1. What makes Quaternions popular in graphics? 
2. Convert a rotation matrix to quaternion and vice versa. Do not use inbuilt libraries for this question.
3. Perform matrix multiplication of two $\mathcal{R}_{3 \times 3}$ rotation matrices and perform the same transformation in the quaternion space. Verify if the final transformation obtained in both the cases are the same.
4. Try to interpolate any 3D model (cube / bunny / not sphere obviously!!) between two rotation matrices and visualize!

The above questions require you to **code your own functions** and **only verify** using inbuilt functions.

<font color='blue' size=4.0/> 2.b.1 What makes Quaternions popular in graphics?

Quaternions allow rotations about multiple axis simultaenously and hence do not suffer from gumbel lock that occurs during sequential rotations about individual axes. Additionally, Quaternions consume less memory and are faster to compute than rotation matrices.

<font color='blue' size=4.0/> 2.b.2 Convert a rotation matrix to quaternion and vice versa.

In [153]:
def rotationToQuaternion(q, R):
    tr = 1 + R[0, 0] + R[1, 1] + R[2, 2]
    return [4*q[0]**2 - tr, 
            4*q[1]*q[2] - (R[0, 1] + R[1, 0]),
            4*q[1]*q[3] - (R[0, 2] + R[2, 0]),
            4*q[2]*q[3] - (R[2, 1] + R[1, 2])]

def quaternionToRotation(q):
    return np.array([[q[0]**2 + q[1]**2 - q[2]**2 - q[3]**2, 2*(q[1]*q[2] - q[0]*q[3]), 2*(q[1]*q[3] + q[0]*q[2])],
                     [2*(q[1]*q[2] + q[0]*q[3]), q[0]**2 - q[1]**2 + q[2]**2 - q[3]**2, 2*(q[2]*q[3] - q[0]*q[1])],
                     [2*(q[1]*q[3] - q[0]*q[2]), 2*(q[2]*q[3] + q[0]*q[1]), q[0]**2 - q[1]**2 - q[2]**2 + q[3]**2]])

def quaternionConjugate(q):
    return q*np.array([1, -1, -1, -1])

In [154]:
rot_mat = N
print("Original Matrix: \n", rot_mat)

Original Matrix: 
 [[ 0.         -0.17364818  0.98480775]
 [ 0.          0.98480775  0.17364818]
 [-1.          0.          0.        ]]


In [160]:
## Convert Rotation Matrix to Quaternion
quaternion = [0.001, 0.001, 0.001, 0.001]
quaternion = fsolve(rotationToQuaternion, quaternion, args=rot_mat)

## Conjugate of quaternion
quaternion_conj = quaternionConjugate(quaternion)

print(f"Quaternion from matrix: {quaternion}")
print(f"Conjugate Quaternion from matrix: {quaternion_conj}")

Quaternion from matrix: [ 0.70441603  0.06162842 -0.70441603 -0.06162842]
Conjugate Quaternion from matrix: [ 0.70441603 -0.06162842  0.70441603  0.06162842]


In [161]:
## Convert Quaternion to Rotation Matrix
rotation_matrix = quaternionToRotation(quaternion)
print("Rotation Matrix from Quaternion: \n", np.around(rotation_matrix, decimals=6))

## Convert Quaternion Conjugate to Rotation Matrix
rotation_matrix = quaternionToRotation(quaternion_conj)
print("Rotation Matrix from Quaternion Conjugate: \n", np.around(rotation_matrix, decimals=6))

Rotation Matrix from Quaternion: 
 [[-0.       -0.       -1.      ]
 [-0.173648  0.984808  0.      ]
 [ 0.984808  0.173648 -0.      ]]
Rotation Matrix from Quaternion Conjugate: 
 [[-0.       -0.173648  0.984808]
 [-0.        0.984808  0.173648]
 [-1.        0.       -0.      ]]


In [162]:
## Verification for Quaternion from Rotation Matrix
r = Rotation.from_matrix(rot_mat)
scipy_quat = r.as_quat()[[-1, 0, 1, 2]]
print("Scipy Result: ", scipy_quat)

Scipy Result:  [ 0.70441603 -0.06162842  0.70441603  0.06162842]


In [163]:
## Verification for Quaternion to Rotation Matrix
r = Rotation.from_quat(scipy_quat[[1, 2, 3, 0]])
print("Scipy Result: \n", np.around(r.as_matrix(), decimals=6))

Scipy Result: 
 [[ 0.       -0.173648  0.984808]
 [ 0.        0.984808  0.173648]
 [-1.        0.        0.      ]]


<font color='blue' size=4.0/> 2.b.3 Perform matrix multiplication of two rotation matrices and perform the same transformation in the quaternion space

In [174]:
def multiplyQuaternions(a, b):
    O = np.outer(a, b)
    return np.array([O[0, 0] - O[1, 1] - O[2, 2] - O[3, 3], 
                     O[0, 1] + O[1, 0] + O[2, 3] - O[3, 2],
                     O[0, 2] + O[2, 0] - O[1, 3] + O[3, 1],
                     O[0, 3] + O[3, 0] + O[1, 2] - O[2, 1]])

In [175]:
R_MN = M @ N
print("Matrix Multiplication:\n", np.around(R_MN, decimals=4))

Matrix Multiplication:
 [[-0.9448 -0.2393  0.2239]
 [-0.1401  0.9126  0.3842]
 [-0.2962  0.3316 -0.8957]]


In [197]:
q_M = [0.001, 0.001, 0.001, 0.001]
q_M = fsolve(rotationToQuaternion, q_M, args=M)
q_M_ = quaternionConjugate(q_M)
print("Qm:\n", q_M, "\nQm':\n", q_M_)

q_N = [0.001, 0.001, 0.001, 0.001]
q_N = fsolve(rotationToQuaternion, q_N, args=N)
q_N_ = quaternionConjugate(q_N)
print("Qn:\n", q_N, "\nQn':\n", q_N_)

Qm:
 [0.79429624 0.00973605 0.59313227 0.13112038] 
Qm':
 [ 0.79429624 -0.00973605 -0.59313227 -0.13112038]
Qn:
 [ 0.70441603  0.06162842 -0.70441603 -0.06162842] 
Qn':
 [ 0.70441603 -0.06162842  0.70441603  0.06162842]


In [194]:
q_MN = np.around(multiplyQuaternions(q_M, q_N), decimals=5)
q_M_N = np.around(multiplyQuaternions(q_M_, q_N), decimals=5)
q_MN_ = np.around(multiplyQuaternions(q_M, q_N_), decimals=5)
q_M_N_ = np.around(multiplyQuaternions(q_M_, q_N_), decimals=5)
print("Qm x Qn:\n", q_MN)
print("Qm' x Qn:\n", q_M_N)
print("Qm x Qn':\n", q_MN_)
print("Qm' x Qn':\n", q_M_N_)

Qm x Qn:
 [ 0.98481  0.11162 -0.13302  0.     ]
Qm' x Qn:
 [ 0.13422 -0.01372 -0.98601 -0.0979 ]
Qm x Qn':
 [ 0.13422 -0.0979   0.96865  0.18473]
Qm' x Qn':
 [ 0.98481  0.       0.15038 -0.08682]


In [206]:
rotation_matrix = quaternionToRotation(q_MN)
print("Rot(Qm x Qn)\n", np.around(rotation_matrix, decimals=5))

rotation_matrix = quaternionToRotation(q_M_N)
print("Rot(Qm' x Qn)\n", np.around(rotation_matrix, decimals=5))

rotation_matrix = quaternionToRotation(q_MN_)
print("Rot(Qm x Qn')\n", np.around(rotation_matrix, decimals=5))

rotation_matrix = quaternionToRotation(q_M_N_)
print("Rot(Qm' x Qn')\n", np.around(rotation_matrix, decimals=5))

print("Rot(Qm x Qn') is same as Original Rotation Matrix Multiplication ")

Rot(Qm x Qn)
 [[ 0.96462 -0.0297  -0.262  ]
 [-0.0297   0.97509 -0.21985]
 [ 0.262    0.21985  0.9397 ]]
Rot(Qm' x Qn)
 [[-9.6360e-01  5.3340e-02 -2.6200e-01]
 [ 7.8000e-04  9.8046e-01  1.9674e-01]
 [ 2.6737e-01  1.8938e-01 -9.4480e-01]]
Rot(Qm x Qn')
 [[-0.94481 -0.23925  0.22385]
 [-0.14007  0.91259  0.38416]
 [-0.29619  0.3316  -0.89573]]
Rot(Qm' x Qn')
 [[ 0.9397   0.171    0.29619]
 [-0.171    0.98493 -0.02611]
 [-0.29619 -0.02611  0.95477]]
Rot(Qm x Qn') is same as Original Rotation Matrix Multiplication 


In [205]:
r = Rotation.from_matrix(R_MN)
scipy_quat = r.as_quat()[[-1, 0, 1, 2]]
print("Scipy Result, Rot => Quat: ", scipy_quat)
print("Result is same as Qm x Qn'")

Scipy Result, Rot => Quat:  [ 0.13422226 -0.09790244  0.96864628  0.18472653]
Result is same as Qm x Qn'


<font color='blue' size=4.0/> 2.b.4 Try to interpolate any 3D model between two rotation matrices and visualize

In [224]:
point_cloud.rotate(R=R_MN)
o3d.visualization.draw([point_cloud, mesh_frame],
                       lookat=np.array([[.0], [.1], [.0]], dtype=np.float64),
                       eye=np.array([[0.0], [0.0], [-0.4]], dtype=np.float64),
                       up=np.array([[0.0], [0.5], [0.0]], dtype=np.float64),
                      )

## c) Exponential maps (Bonus)

1. What is the idea behind exponential map representation of rotation matrices?
2. Perform matrix exponentiation and obtain the rotation matrix to rotate a vector $P$ around $\omega$ for $\theta$ seconds.
$$
\omega = \begin{bmatrix}2 \\ 1 \\ 15 \end{bmatrix}
$$

$$
\theta = 4.1364
$$

3. Compute the logarithmic map (SO(3) to so(3)) of the rotation matrix to obtain the rotation vector and the angle of rotation
$$
\begin{bmatrix}
0.1 &  -0.9487 & 0.3 \\
0.9487 & 0.  & -0.3162 \\
0.3   &  0.3162  & 0.9 
\end{bmatrix}
$$
You can use inbuilt libraries **only to verify** your results.

# 3. Data representations

## a) Octomaps

1. Why is an Octomap memory efficient?
2. When do we update an Octomap and why?
3. When would you likely use an octomap instead of a point cloud?
 

## b) Signed Distance Functions

1. How do we determine object surfaces using SDF?
2. How do we aggregate views from multiple cameras? (just a general overview is fine)
3. Which preserves details better? Voxels or SDF? Why?
4. What’s an advantage of SDF over a point cloud?


# References and Resources

1. Gimbal locks and quaternions: https://youtu.be/YF5ZUlKxSgE
2. Exponential map: 
    1. 3 Blue 1 Brown: https://youtu.be/O85OWBJ2ayo
    2. Northwestern Robotics: https://youtu.be/v_KBHaG0mas
3. Bunny ply is taken from: http://graphics.im.ntu.edu.tw/~robin/courses/cg03/model/